definitions:
  handler.Error:
    properties:
      message:
        type: string
    type: object
  handler.ShortenInput:
    properties:
      url:
        type: string
    type: object
  url.ShortenBatchInput:
    properties:
      correlation_id:
        type: string
      original_url:
        type: string
      shortenURL:
        type: string
      userID:
        type: string
    type: object
info:
  contact: {}
  title: Go Shortener App API
  version: "1.0"
paths:
  /{id}:
    get:
      consumes:
      - application/json
      description: Get shorten url
      parameters:
      - description: shorten url id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Error'
        "410":
          description: Gone
      summary: Get Shorten
  /api/shorten:
    post:
      consumes:
      - application/json
      description: Create new shorten URL
      parameters:
      - description: url
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.ShortenInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Create JSON Shorten
  /api/shorten/batch:
    post:
      consumes:
      - application/json
      description: Create new shorten batch of URLS
      parameters:
      - description: url
        in: body
        name: input
        required: true
        schema:
          items:
            $ref: '#/definitions/url.ShortenBatchInput'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/url.ShortenBatchInput'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Create JSON Shorten Batch
swagger: "2.0"
